spring:
  application:
    name: ShoppingApp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Aba32835
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
    port: 8081

